### PR TITLE
first attempt to build sdk

### PR DESCRIPTION
**Pull request by wfurt**

### CODE REVIEW

**Comment by wfurt** [comment]
Outcome should be in  installer/artifacts/bin/redist/Release/dotnet/sdk/

I need more testing. TBD combining with runtime.
This generally fetches various pre-built bits and puts them together. 

Since this is so short we may consider combing it with runtime. 

cc: @am11

**Comment by wfurt** [comment]
related to #8

**Comment by am11** [comment]
Would be nice if we keep everything in .cirrus.yml for now, and later move things around once all pieces including test runs are in place. I am not sure if we still want to clone old repos in `checkout.sh`.

Besides, isn't is so that the installers are already built as part of our `runtime/build.sh ...` on line 19, or do we need https://github.com/dotnet/installer/ repo? For latter, I would just use line 14 way of flat cloning rather than using checkout script.

**Comment by wfurt** [comment]
What I realized yesterday, that when logic is build to .cirrus.yml then it is harder to test this locally. (and readme is completely out of date) So I was thinking about moving everything to scripts/* and have  .cirrus.yml calling that and README explaining the steeps.

And yes, we need  https://github.com/dotnet/installer/ repo if we want to get SDK as well. The runtime/src/installer build core host e.g. dotnet binary it self. Together with the other parts it gives you runtime and ability to run managed code. 
The installer repo bundles SDK e.g. msbuild, Roslyn etc. I need to do more testing but this is part where I realized that it would be handy to build and have bits without Cirrus.

Aside from running test, It may be worth of adding test step to do `dotnet new console` and `dotnet run` on FreeBSD. 

cc: @jasonpugsley

**Pull request merged**
